server:
  port: 9000

spring:
  application:
    name: cards
  datasource:
    url: jdbc:mysql://localhost:3308/cards_db
    username: root
    password: mysql_pwd
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"

# Moved below properties to spring cloud config server
#
# build:
#   version: "3.0"
#
# cards:
#   message: "Welcome to EazyBank cards related local APIs "
#   contactDetails:
#     name: "Dragos Lech - Developer"
#     email: "cards@eazybank.com"
#   onCallSupport:
#     - (412) 419-3491
#     - (915) 382-1932

management:
  endpoints:
    web:
      exposure:
        include: "refresh,busrefresh"
