server:
  port: 8090

spring:
  application:
    name: loans
  datasource:
    url: jdbc:mysql://localhost:3307/loans_db
    username: root
    password: mysql_pwd
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"

# Moved below properties to spring cloud config server
#
# build:
#   version: "3.0"
#
# loans:
#   message: "Welcome to EazyBank loans related local APIs "
#   contactDetails:
#     name: "Amaal Grega - Developer"
#     email: "loans@eazybank.com"
#   onCallSupport:
#     - (452) 456-2176
#     - (546) 764-8934

management:
  endpoints:
    web:
      exposure:
        include: "refresh,busrefresh"
