build:
  version: "loans_default_1.0"

loans:
  message: "Welcome to eazybytes bank Loans Default microservice API."
  contactDetails:
    name: "Loans Default Name"
    email: "loans_default@email.com"
  onCallSupport:
    - (111) 111-1111
    - (111) 111-1112
